config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  resources :users, only: [:show] do
    resources :concepts
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :user
  belongs_to :section, optional: true

  validates :title, presence: true
  validates :description, presence: true

end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :section, optional: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :languages
  has_many :concepts
  has_many :users, through: :concepts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :concepts
  has_many :sections, through: :concepts#,source: :sections

  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      if auth.info.email != nil 
      #If the email address on a github profile is private,
      #something needs to be provided for validation
        user.email = auth.info.email
      else
        user.email = "blank@gmail.com"
      end
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.save!
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private

  def set_user
    @user = current_user
  end

  protected
  
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end


end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  def index
    @user = current_user
    @concept = Concept.new

    @favorites = @user.concepts.favorited
    @remaining_concepts = @user.concepts.not_favorited

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @remaining_concepts}
    end
  end   

  def new
    @user = current_user
    @concept = Concept.new
  end

  def create
    @user = current_user
    @concept = @user.concepts.build(concept_params)
    
    if @concept.save
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @concept}
      end

      flash[:notice] = "Thank you for your submission!"
    else
      render :new
      flash[:alert] = "Unfortunately your concept was not saved."
    end
  end

  def show
    @user = current_user
    @concept = Concept.find(params[:id])
  end

  def edit
    @user = current_user
    @concept = Concept.find(params[:id])
  end

  def update
    @user = User.find_by_id(params[:user_id])
    @concept = Concept.find(params[:id])
    if @concept.update(concept_params)
      flash[:notice] = "Thanks for the update!."
      redirect_to user_concept_path(@concept)
    else
      flash[:alert] = "Update unsuccessful."
      render :edit
    end
  end

  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy
    flash[:notice] = "Concept deletion successful"
    redirect_to user_concepts_path(current_user)
  end

  private

  def concept_params
    params.require(:concept).permit(
      :title,
      :description,
      :favorited,
      :user_id,
      :section_id,
      :user => [:id, :name, :email, :name, :display_name]
      )
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    binding.pry
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  
  def index
    @sections = Section.all
  end

  def show
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

 
  private
 
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @user}
    end
  end

  def user_params
    params.require(:user).permit(:id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@user = User.all[0]
		@concept = @user.concepts.sample

		respond_to do |format|
      format.html {render :index}
			format.json {render json: @concept}
    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource_class 
    User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML

   <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>Unsuccessful</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concepts/_form.html.erb
<div>
  <h4>New Concept </h4>
  <%= form_for [@user, @concept] do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <br>
    <p>
      <%= f.label :description, "Tell us about your app idea!" %><br>
      <%= f.text_area :description%>
    </p>
    <p>
      <%= f.label :favorited, "Save as favorite?" %>
      <%= f.check_box :favorited%>
    </p>

    <%= f.submit "Submit Concept!", :class=> "btn btn-primary" %>
  <% end %>
</div>

app/views/concepts/_form_edit.html.erb
<h3> Edit Your Concept</h3>
<%= form_for @concept, url: user_concept_path(@user) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :description, "Edit your Concept's description:" %> <br>
  <%= f.text_area :description, class: "form-control col-9" %>
  <br>

  <%= f.label :favorited, "Do you love your new concept? Save it for later!" %>
  <%= f.check_box :favorited%>
  
  <br>
  <%= f.submit "Submit Your Edits", :class=> "btn btn-primary" %>
<% end %>

app/views/concepts/_index.html.erb
<h5>Add a new Concept </h5><br>
<%= form_for [@user, @concept], :html => { :id => "append_new_concept" } do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description, "Tell us about your app idea!" %><br>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.label :favorited, "Love your idea? Save it for later!" %>
    <%= f.check_box :favorited%>
  </p>

  <%= f.submit "Submit Concept!", :class=> "btn btn-primary" %>
<% end %>

app/views/concepts/edit.html.erb
<%= render 'concepts/form_edit' %>

app/views/concepts/favorites.html.erb
<h1>Favorited Concepts!</h1>

<ul>
  <% @favorite_concepts.each do |favorite_concept| %>
    <li><%= link_to favorite_concept.title, user_concept_path(current_user, favorite_concept) %></li>
  <% end %>
</ul>

app/views/concepts/index.html.erb
<div class="container">
  <div class="col-md-6" id="show-concepts-list-table">
    <h5> Favorite Concepts! </h5>
    <% @favorites.each do |concept| %>
      <%= link_to "#{concept.title}", user_concept_path(concept.user_id, concept.id) %><br>
    <% end %>
    <%= link_to "Unfavorited", user_concepts_path(@user, @concept), class: "col-5 center btn btn-info remainingConcepts notFavs"  %>
    <div id="notFavs">
    </div>
  </div>

  <div class="col-md-3" id="freshConcept">
    <%= render "concepts/index" %>
  </div>
</div> 

app/views/concepts/new.html.erb
<div class="container center-box">
  <div id="newForm">
    <%= render "concepts/form" %>
  <div>
<div>

app/views/concepts/show.html.erb
<div class="container">
  <div class="col-md-6" id="show-table">
    <h2 class= "concept-title text-center"><%= @concept.title.upcase %></h2> <br>

    <strong>Description</strong>
    <p><%= @concept.description %></p>

    <% if @concept.favorited %>
      <p>Favorited♥! (Saved to your favorites list) </p>
    <% end %>

    <div>
      <%= link_to "Edit Concept", edit_user_concept_path(@user, @concept), class: "my-edit-button"  %>
      <%= button_to "Delete Concept", user_concept_path(@user, @concept), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'my-delete-button' %>
    </div>
  </div>
</div>

app/views/sections/index.html.erb
<% @sections.each do |section| %>
   <a  href="#"> <%= section.title %> </a>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="my-button" id="testing-bruh">
    Test!
  </div>

</div>

app/views/users/show.html.erb
<h3><%= @user.display_name %>'s Profile! </h3>
<h4>No idea what to put here yet! </h4>
<h5>(Maybe user account settings?) </h5>