config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  resources :users, only: [:show] do
    resources :concepts
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :user
  belongs_to :section, optional: true

  validates :title, presence: true
  validates :description, presence: true

end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :section, optional: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :languages
  has_many :concepts
  has_many :users, through: :concepts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :concepts
  has_many :sections, through: :concepts#,source: :sections

  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      if auth.info.email != nil 
      #If the email address on a github profile is private,
      #something needs to be provided for validation
        user.email = auth.info.email
      else
        user.email = "blank@gmail.com"
      end
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.save!
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private

  def set_user
    @user = current_user
  end

  protected
  
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end


end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  def index
    @user = current_user
    @concept = Concept.new

    @favorites = @user.concepts.favorited
    @remaining_concepts = @user.concepts.not_favorited

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @remaining_concepts}
    end
  end   

  def new
    @user = current_user
    @concept = Concept.new
  end

  def create
    @user = current_user
    @concept = @user.concepts.build(concept_params)
    
    if @concept.save
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @concept}
      end

      flash[:notice] = "Thank you for your submission!"
    else
      render :new
      flash[:alert] = "Unfortunately your concept was not saved."
    end
  end

  def show
    @user = current_user
    @concept = Concept.find(params[:id])
  end

  def edit
    @user = current_user
    @concept = Concept.find(params[:id])
  end

  def update
    @user = User.find_by_id(params[:user_id])
    @concept = Concept.find(params[:id])
    if @concept.update(concept_params)
      flash[:notice] = "Thanks for the update!."
      redirect_to user_concept_path(@concept)
    else
      flash[:alert] = "Update unsuccessful."
      render :edit
    end
  end

  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy
    flash[:notice] = "Concept deletion successful"
    redirect_to user_concepts_path(current_user)
  end

  private

  def concept_params
    params.require(:concept).permit(
      :title,
      :description,
      :favorited,
      :user_id,
      :section_id,
      :user => [:id, :name, :email, :name, :display_name]
      )
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  
  def index
    @sections = Section.all
  end

  def show
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

 
  private
 
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user

    respond_to do |format|
      format.html {render :index}
      format.json {render json: @user}
    end
  end

  def user_params
    params.require(:user).permit(:id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@user = User.all[0]
		@concept = @user.concepts.sample

		respond_to do |format|
      format.html {render :index}
			format.json {render json: @concept}
    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource_class 
    User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML

   <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>Unsuccessful</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm bg-light" style="background-color: #A9A9A9;">
  <a class="navbar-brand" href="/">Concept Community</a>

  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ml-auto">
      <% if signed_in? %>

        <li class="nav-item active">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Your Concepts", user_concepts_path(current_user), class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "New Concept", new_user_concept_path(current_user.id), class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

      <% else %>

        <li class="nav-item active">
          <%= link_to 'Log in with Github!', user_github_omniauth_authorize_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Concept Community</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    "application", :media => "all"  %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>

      <%= yield %>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  </body>
</html>